#!/bin/bash

# print name
echo "$0"

# stop and disable the access point services
sudo systemctl daemon-reload
sudo systemctl enable hostapd
sudo systemctl start hostapd
sudo systemctl enable dnsmasq
sudo systemctl start dnsmasq

# link to disable
ln -sfv $(dirname $0)/multi_ear_disable_access_point_mode \
        $(dirname $0)/multi_ear_switch_access_point_mode

exit 0
