#!/bin/bash

echo $0
echo $(dirname $0)
exit

# stop and disable the access point services
sudo systemctl daemon-reload
sudo systemctl disable hostapd
sudo systemctl stop hostapd
sudo systemctl disable dnsmasq
sudo systemctl stop dnsmasq

# link to enable
ln -sfv $(dirname $0)/multi_ear_enable_access_point_mode \
        $(dirname $0)/multi_ear_switch_access_point_mode


exit 0
