#!/bin/bash

##############################################################################
# Script Name	: append_wpa_supplicant
# Description	: Append an ssid and the auto-encrypted passphrase to the
#                 wpa_supplicant configuration file.
# Args          : <ssid> <passphrase>
# Author       	: Pieter Smets
# Email         : mail@pietersmets.be
##############################################################################

# Set script name
SCRIPT="append_wpa_supplicant"

# Init
CONF="/etc/wpa_supplicant/wpa_supplicant.conf"

# Message to display when bad usage.
function badUsage
{
    local message="$1"
    local txt=(
"Append an ssid and the auto-encrypted passphrase to the wpa_supplicant configuration file."
"Usage: $SCRIPT <ssid> <passphrase>"
    )

    [[ $message ]] && printf "\n$message\n"

    printf "%s\n" "${txt[@]}"
    exit -1
}

# Check input arguments
if (($# != 2 )); then
    badUsage "Illegal number of arguments"
fi

# Add empty line if wpa_supplicant.conf exists
if [ -f $CONF ];
then
    echo "" | /usr/bin/sudo /usr/bin/tee -a $CONF
else
    badUsage "wpa_supplicant configuration file \"$CONF\" doesn't exist!"
fi

# Encrypt psk and add to wpa_supplicant.conf
/usr/bin/wpa_passphrase $1 $2 |  /usr/bin/sed '3d;2i\\tscan_ssid=1' | /usr/bin/sudo /usr/bin/tee -a $CONF

# Trigger connection
/usr/bin/sudo /usr/bin/systemctl start multi-ear-wifi.service

# Done
exit 0
