#!/bin/bash

##############################################################################
# Script Name	: 7
# Description	: Triggered by gpio-watch for pin 7.
# Args          : n.a.
# Author       	: Pieter Smets
# Email         : mail@pietersmets.be
##############################################################################

/bin/bash /home/tud/.py37/bin/multi-ear-wifi --switch
